### ISSUE TITLE
pistache multi thread example

### ISSUE THREAD

**Issue by forkballpitch** [pistacheio/pistache#242]
I was looking for a thread pistache example.
Could I get a multi thread example~?
i'd like to make a thread class to override an onRequest mothod.
Any suggestions on how I can work around this problem?

thank you!

**Comment by hydratim** [comment]
The reason there is no dedicated multi-thread example is because Pistache is natively multi-threaded so all the examples are technically multi-threaded.
See https://github.com/oktal/pistache/blob/master/examples/http_server.cc and https://github.com/oktal/pistache/blob/master/examples/rest_server.cc for more detail.
