### ISSUE TITLE
[FEATURE REQUEST] used std::optional if available

### ISSUE THREAD

**Issue by jacobbogdanov** [pistacheio/pistache#858]
`Pistache::Optional` has a slight, but noticeably, different interface to c++17's `std::optional`. Similar to how `include/pistache/string_view.h` uses c++17's `std::string_view` if available, it would be nice if `Pistache::Optional` could be an alias for `std::optional` using the same `__has_include` trick to only conditionally build the custom implementation.

Here are the API differences between the pistache and the standard,
| `pistache::Optional` | `std::optional`|
|---------------------|---------------|
| `getOrElse` | [`value_or`](https://en.cppreference.com/w/cpp/utility/optional/value_or) |
| `isEmpty` | [`has_value`](https://en.cppreference.com/w/cpp/utility/optional/has_value) |
| `get` | [`value`](https://en.cppreference.com/w/cpp/utility/optional/value)/[`operator*`](https://en.cppreference.com/w/cpp/utility/optional/operator*) |
| `Pistache::types::None` | [`std::nullopt_t`](https://en.cppreference.com/w/cpp/utility/optional/nullopt_t) |
| `Pistache::types::Some` | [`std::optional::optional`](https://en.cppreference.com/w/cpp/utility/optional/optional) has `T` constructors |
| - | `std::is_trivial<std::optional<T>>::value == std::is_trivial<T>::value`  |
| - | modifiers: [`swap`](https://en.cppreference.com/w/cpp/utility/optional/swap),  [`reset`](https://en.cppreference.com/w/cpp/utility/optional/reset),  [`clear`](https://en.cppreference.com/w/cpp/utility/optional/clear) |

## Describe the solution you'd like
Seeing how different the implementation is, it may be worth importing a c++11 compatible `std::string_view` implementation.
For example, ~~[`string_view-standalone`](https://github.com/bitwizeshift/string_view-standalone) (licensed MIT,)~~* [`tl::optional`](https://github.com/TartanLlama/optional) could replace the current optional implementation, if the `__has_include(<optional>)` check fails.

This is an API breaking change, as downstream users will need to update their usage. In the code base that I work in, the only usage of `Pistache::Optional` that would need to be updated are, `getOrElse` -> `value_or`, `isEmpty` -> `has_value`, and `.get()` -> `.value()` (or `operator->`,) as we never construct or pass `Pistache::Optional`'s outside of the initial extraction of data from a request.

* edit: had a brain fart and posted a `std::string_view` alternative, not a `std::optional` alternative.

**Comment by kiplingw** [comment]
Thanks @jacobbogdanov. I'm not sure if this helps, but something most people may not know about our `Pistache::Optional` implementation is the storage for the payload always exists, regardless of whether there is a "live" object within it or not. 

When a value is set, the code uses placement new to construct in place within the storage already allocated. 
The reason for this is the cost / benefit in a high performance library favoured reduced time in not having to potentially perform a memory allocation later at the reasonable cost of increased storage. This is different from the STL's implementation which only allocates when set.

**Comment by jacobbogdanov** [comment]
That's also guaranteed by the standard

> Any instance of `optional<T>` at any given time either contains a value or does not contain a value. When
an instance of `optional<T>` contains a value, it means that an object of type `T`, referred to as the optional
object’s contained value, is **allocated within the storage of the optional object. Implementations are not
permitted to use additional storage**, such as dynamic memory, to allocate its contained value. The contained
value shall be allocated in a region of the `optional<T>` storage suitably aligned for the type `T`. 

23.6.3 [optional.optional]

**Comment by kiplingw** [comment]
You're right! I didn't know that.

Eventually we will probably drop it. But since the STL's version didn't arrive until C++17, and we're still trying to not create issues for users relying on C++14, sadly we still need to maintain it for at least another year or two. 

I think the main reason why @oktal came up with the interface that he did was for consistency in naming convention with the rest of the library, and also the fact that he began writing the library in 2015 before he probably knew what to expect in the 2017 STL.

**Comment by hadrielk** [comment]
How about this:

1. Add the same `std::optional` function names into `Pistache::Optional`, without getting rid of the existing ones - basically make them just invoke the current functions. That allows the API of `Pistache::Optional` to migrate over time to `std::optional`.
2. Provide a CMake option for using `std::optional` instead of `Pistache::Optional`, which by default is OFF.
3. Create a "`#define PISTACHE_OPTIONAL Pistache::Optional`" if that CMake option is OFF, but instead defines it as "`#define PISTACHE_OPTIONAL std::optional`" if it's ON.
4. Use `PISTACHE_OPTIONAL` for the type, everywhere in Pistache.
5. Change any _internal_ uses of `Pistache::Optional`'s functions (internally used inside `Pistache`'s own code) to use the new function names - that way swapping the type out by setting the CMake option won't break anything.
6. Profit?

(it doesn't have to be a `#define` macro name - it could be a `typedef` or `using` alias instead)

**Comment by kiplingw** [comment]
Another option is we strip `Pistache:Optional` out entirely, use the STL's, and update the requirements to use C++17. There's a couple good reasons for this:

- We don't have a stable release yet, so users are expected to be using a bleeding edge library. That should give us greater license to be less constrained in accommodating anything legacy;
- Less code to maintain;
- The STL's implementation will probably be very fast anyways, if not faster;
- In removing it, we don't need to change `Pistache::Optional`'s interface to be consistent with the STL's because it would actually be;
- By moving to C++17, we can leverage all the other syntactic sugar the language offers in other places in the library.

**Comment by oktal** [comment]
Hi guys,

To complement on what @kiplingw said, I had to roll out my own `Optional<T>` because it was not available at that time, when I first started to implement this library, back in 2015-2016 (I think it was in the `std::experimental` namespace).

I'm not a big fan of the STL interface that does not really ensure type-safety, that's why I took the "functional" route with a `Some(T)` and `None` types approach.

That being said, I'm not against using the `optional` type from the standard library (I'm actually using it in other projects too), so I think we should go ahead with what you're proposing and replace Pistache' `Optional` with `std::optional`.
