### ISSUE TITLE
[FEATURE REQUEST] Windows Support

### ISSUE THREAD

**Issue by kyro-dev** [pistacheio/pistache#869]
Is the pistacheio team planning to add support for windows? I'm developing on windows and I would really like to use your library.

**Comment by Tachi107** [comment]
As mentioned in #6, #538 and #649, it would not be an easy task, especially because the issue is related to architectural decisions. In the meantime you could use WSL, or maybe try out Linux ;) 

Anyway, I don't think that opening another issue will improve the situation, also because #538 is still open; I think you can close this, thanks

**Comment by kyro-dev** [comment]
Ok, thanks anyways.
