### ISSUE TITLE
Is the client code production ready?

### ISSUE THREAD

**Issue by Leon0402** [pistacheio/pistache#894]
Hi, 

I saw that pistache comes with a client library, but I wasn't sure if it's something that is actively developed and / or production ready. I saw a comment on this a year back: https://github.com/pistacheio/pistache/issues/673#issuecomment-575947083, which states that the client lib is not ready and kinda abandoned.

Is providing a good, feature-rich client library even a goal of pistache? 
What ist the current progress? 

I'm also confused by the facts that you seem to use https://github.com/pistacheio/pistache/blob/master/tests/httplib.h another http lib for your tests, which you seem to use as the client for the server test.

Is it recommended to use that lib as well instead? Or do you recommend some other lib? 

Thanks for the clarification! Perhaps putting a note in the readme about the current state of the server / client lib (especially if it's actively developed & production-ready) would be very helpful.

**Comment by Tachi107** [comment]
I think that Pistache's main focus is (or should be?) to provide a good REST framework. It also has a client that seems to work, but I wouldn't recommend using it. I personally use [`libcurl`](https://github.com/curl/curl); it is fast and stable, but it is written in C and its interface is far from elegant and using it asynchronously is complicated to say the least. 

Since I've never used it that much I can't say if people should or shouldn't use it, but judging from the issue tracker it looks like it is not production ready.

**Comment by Leon0402** [comment]
Thanks for clarification! As I said I think this should perhaps be part of the readme. 

What is the state of the server code? it's production ready, right? 

Thanks for the suggestons with `libcurl`. I'll have a look. But would also be happy for more suggestions.

**Comment by kiplingw** [comment]
@Tachi107, I think he raises a good point that the client library's current unusable state should probably be in the readme. If you'd like to propose a PR, I will review and merge.
