### ISSUE TITLE
Add Release

### ISSUE THREAD

**Issue by Leon0402** [pistacheio/pistache#913]
## Is your feature request related to a problem? Please describe.

Please release a version of pistache with a git tag. Even if it's some alpha release or whatever. When using the project with FetchContent I want to check out a tag for two reasons: 

* So CMake doesn't redownload every time someone adds a commit 
* I can be certain that things don't suddenly break (which doesn't happen if I always use the same version)

Obviously it would be great to use some sort of semantic versioning. But for now I would be totally fine if you just add a "28-04-2021" tag or whatever. No need to wait until some specific thing is implemented or fixed.

**Comment by kiplingw** [comment]
Thanks @Leon0402. We still have more work to do before we are ready for a 1.0 release. But you shouldn't be using the source directly in your project's tree anyways, unless you are making modifications.

There is a pkg-config manifest that ships within the precompiled binaries in the unstable PPA that you should try to use.

**Comment by Leon0402** [comment]
Hi @kiplingw using FetchContent is the normal and I would say actually recommended approach to use libraries in C++ with CMake. Especially rather small ones (-> Everything except things like Qt, Boost). 

It would be great if you support this standard way of including the lib even if you are of a different opinion.

**Comment by kiplingw** [comment]
There's actually a number of reasons why that's not a good idea. Here's a couple:

- pkg-config is the result of XDG standardization;
- FetchContent is unique to CMake;
- Including source in your source tree is a maintenance nightmare;
- Users are required to have all build dependencies for your project's dependencies themselves whenever you include source in the tree;
- pkg-config manifests ship with the system package manager's packages normally. FetchContent doesn't track what it pulls. This means installing from source can leave artefacts on your system and can pollute your paths. The system package manager doesn't have that problem;
- FetchContent cannot automatically ensure that what it pulls can be reconciled with installed binaries;
- Many other reasons I don't have time to get into :)

As for the version number, it's arbitrary. But there are two versioning schemes that are unrelated to each other. These are the project version and the SONAME version, both of which the system package manager is aware of. See the readme for more details.

**Comment by Leon0402** [comment]
> pkg-config is the result of XDG standardization;

Sure. And FetchContent is a CMake Standard :) Pistache is no desktop installation, it's a dependency in my project. And for sure my project, which is an application, will respect the XDG Standard as it will be installed on the server. 
But there is no need to install Pistache on my Computer. 

> FetchContent is unique to CMake

You don't have to drop pkg-config. But CMake is the standard in the C++ World and if you use CMake the support for FetchContent comes almost for free (in fact you library works perfectly fine with FetchContent right now, except the fact that I have to use the master branch, which changes and which is obviously bad) 

> Including source in your source tree is a maintenance nightmare;

Yes! That's the reason why it's not. FetchContent fetches the sources from GitHub and puts them in the build directory. There is no mainenance problem. In fact it's the most easiest and convenient option to use a library with cmake. 
This is for a couple of reasons: 
- It's easy for the library author. Because you just write your normal CMake Code and it just works^TM :) You might know what you need to do to fully support find_package ... it's honestly a little nightmare. 
- Every developer can just build the project on every OS without installing anything. Because CMake just downloads the sources and builds it for you. Super convenient! 
  -> What is if you don't have a debian linux System? And you don't have prebuilt libraries?
- It has perfect CMake Integration! Because you just can work with CMake Targets. You can do this with find_package as well, but it something the library needs to support and it's not straight forward.
- You can easily switch versions. You can even use alpha version or development branches if you need to (and sometimes you need). That's some huge advantage over a package manager 
- You can actually control what you need. Because the project is included via add_subdirectory you can just set variables as you want. Don't want the Client Library of pistache -> set BUILD_PISTACHE_CLIENT to false (assuming such a variable exists) 
- And Many other reasons I don't have time to get into 

> pkg-config manifests ship with the system package manager's packages normally. FetchContent doesn't track what it pulls. 

FetchContent tracks what it pulls. You can specify a Git Tag or a branch and a couple of other thing, no problems. 

> This means installing from source can leave artefacts on your system and can pollute your paths. The system package manager doesn't have that problem;

FetchContent always pulls the library into the build folder. It's never installed on the system and can therefore never pollute any path. 

> FetchContent cannot automatically ensure that what it pulls can be reconciled with installed binaries; 

I'm not sure what you mean? If you have installed pistache additionally on your system, it doesn't matter. Those don't conflict.



I just want to mention that a lot of languages have similar concepts. Some have it's own package manager (like pip for Python, maven for Java, gem for ruby ... you name it) and a lot of languages / package manager also have support for installing stuff from GitHub directly (like gem for ruby, poetry for pyhon ... you name it). There is a reason for this. 
The System Package Manager is great, I love it! But's it's for end users, for the system and not made for developement. Having multiple versions of a package, easily switching between them, trying out alpha releases and unstable development code is something you need for development and something the system package Manager is not particularly good at. 
Furthermore it's highly system dependent (do you even have up to date packages? Is there a package for your system?). 
And having a huge documentation on how to setup all development dependencies for your library is something that will keep developers away. Nobody wants to spend 1 hour on getting everything to work, just to make a small PR. 

These are some points on the very long list of reasons, why you usually don't use a System Package Manager for development. Except for very well known and / or stable and / or large stuff. 

FetchContent is one of a few ways to solve some of these issues with C++ / CMake. And it's a good way imo. Another would be using something like Conan (which is a C++ Package Manager). 



> As for the version number, it's arbitrary. But there are two versioning schemes that are unrelated to each other. These are the project version and the SONAME version, both of which the system package manager is aware of.

If there is a already a project version. Why not just tag it with git? 


I believe that you have you very good reasons to use the System Package Manager. I do this as well with some libraries. I tried to give you some reasons why FetchContent is a good option and it's worth it to support it and might even take a closer look at for yourself. It's not as bad as you think. If you still believe the system package manager is better, that's fine. You can have your preference as I have mine. But please don't just say "It's bad practise, don't do it, won't support it". It's definitely not! :-) 

Based on your argument, it seems like you're confusing FetchContent with the "I just clone the project in a subfolder in my source tree" Approach -> That's definitely bad practise, but it's not Fetch Content :)

**Comment by kiplingw** [comment]
> Sure. And FetchContent is a CMake Standard :) 

CMake is not a standard. It's not even an implementation of a standard. It's a build tool among a constellation of build tools.

> Pistache is no desktop installation, it's a dependency in my project. 

That doesn't make sense. If it's a build and runtime dependency, and I'm assuming that's what you mean, then it needs to be present on the end user's machine. The standard way to ensure that is to use the system package manager. Statically linking is a security risk and a maintenance nightmare, as is well accepted in the UNIX world.

> And for sure my project, which is an application, will respect the XDG Standard as it will be installed on the server.

I'm not sure which XDG (freedesktop.org) specification you are referring to. If you are talking about pkg-config, it isn't used to install applications. It's used by build environments to locate dependencies and supply the build tools with the correct compilation and linker flags.

> But there is no need to install Pistache on my Computer.
> 
> > FetchContent is unique to CMake
> 
> You don't have to drop pkg-config. But CMake is the standard in the C++ World and if you use CMake the support for FetchContent comes almost for free (in fact you library works perfectly fine with FetchContent right now, except the fact that I have to use the master branch, which changes and which is obviously bad)

CMake is not a "standard" in the C++ world. As I said, it's not even an implementation of a standard. It is a build tool among a constellation of options.

Master branch changes regularly because that's why it's master. There is no stable branch because we don't have a stable release.

> > Including source in your source tree is a maintenance nightmare;
> 
> Yes! That's the reason why it's not. FetchContent fetches the sources from GitHub and puts them in the build directory. There is no mainenance problem. In fact it's the most easiest and convenient option to use a library with cmake.

That's even worse. That means every time you clean your build prefix you lose an entire dependency for an external library.

> This is for a couple of reasons:
> 
>     * It's easy for the library author. Because you just write your normal CMake Code and it just works^TM :) You might know what you need to do to fully support find_package ... it's honestly a little nightmare.

It's not easier for the reasons I already explained.

>     * Every developer can just build the project on every OS without installing anything. Because CMake just downloads the sources and builds it for you. Super convenient!

What you are trying to achieve is what a system package manager does already. Apt can even download the source (though there is rarely a need), including build dependencies.

>       -> What is if you don't have a debian linux System? And you don't have prebuilt libraries?

Then provide a PR for your distro's system package manager. If the Debian Policy Manual isn't an option for you, then there are others like RPMs.

>     * It has perfect CMake Integration! Because you just can work with CMake Targets. You can do this with find_package as well, but it something the library needs to support and it's not straight forward.

Already responded to this.

>     * You can easily switch versions. You can even use alpha version or development branches if you need to (and sometimes you need). That's some huge advantage over a package manager

You can pin a package at a particular version, provide custom patched packages via quilt, and do all of this from your own apt repository (e.g. a PPA).

>     * You can actually control what you need. Because the project is included via add_subdirectory you can just set variables as you want. Don't want the Client Library of pistache -> set BUILD_PISTACHE_CLIENT to false (assuming such a variable exists)

Or you can just use [FindPkgConfig](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) for CMake and accomplish the same in a more portable manner.

> FetchContent tracks what it pulls. You can specify a Git Tag or a branch and a couple of other thing, no problems.

No it doesn't. If you already have the dependency on your system or a conflicting library installed, it won't know that.

> FetchContent always pulls the library into the build folder. It's never installed on the system and can therefore never pollute any path.

If it's in the build prefix it has already polluted the path because the user may have already had the dependency installed through the system package manager and your build environment will automatically override the user's preference and use something from somewhere else.

> I'm not sure what you mean? If you have installed pistache additionally on your system, it doesn't matter. Those don't conflict.

Please read the pkg-config documentation and the DPM so you have an idea of the types of problems they are intended to solve.

> I just want to mention that a lot of languages have similar concepts. Some have it's own package manager (like pip for Python, maven for Java, gem for ruby ... you name it) and a lot of languages / package manager also have support for installing stuff from GitHub directly (like gem for ruby, poetry for pyhon ... you name it). There is a reason for this.

Yes, and they are all bad ideas for some of the reasons I've already covered. Artifacts, dependency reconciliation and calculation, violating the FHS, poor security, and many others.

> The System Package Manager is great, I love it! But's it's for end users, for the system and not made for developement. 

Unfortunately you're mistaken again. Apt is designed for both. That's why the DPM provides a `Build-Depends:` stanza. I strongly suggest reading the documentation.

> Having multiple versions of a package, easily switching between them, trying out alpha releases and unstable development code is something you need for development and something the system package Manager is not particularly good at.

You can do all of that with Apt.

> Furthermore it's highly system dependent (do you even have up to date packages? Is there a package for your system?).

Again, you need to do more reading. We've had an unstable PPA for over a year now that produces nightlies.

> And having a huge documentation on how to setup all development dependencies for your library is something that will keep developers away. Nobody wants to spend 1 hour on getting everything to work, just to make a small PR.

Like what CMake requires you to do? If you want to install all build dependencies for a project, it's as simple as running `$ sudo apt build-dep myproject`.

> These are some points on the very long list of reasons, why you usually don't use a System Package Manager for development. Except for very well known and / or stable and / or large stuff.

It sounds like your experience is limited if you believe that.

> FetchContent is one of a few ways to solve some of these issues with C++ / CMake. And it's a good way imo. Another would be using something like Conan (which is a C++ Package Manager).

Language package managers are only helpful if you are using a platform that is crippled because it still doesn't have a system package manager in 2021.

> If there is a already a project version. Why not just tag it with git?

Because we don't have a stable version. Not having a stable release and having a project version are not mutually exclusive.

> I believe that you have you very good reasons to use the System Package Manager. I do this as well with some libraries. I tried to give you some reasons why FetchContent is a good option and it's worth it to support it and might even take a closer look at for yourself. It's not as bad as you think. If you still believe the system package manager is better, that's fine. You can have your preference as I have mine. But please don't just say "It's bad practise, don't do it, won't support it". It's definitely not! :-)

Ask yourself how many "packages" are available for CMake, and then ask yourself if it compares to the over 58,000 via Apt.

> Based on your argument, it seems like you're confusing FetchContent with the "I just clone the project in a subfolder in my source tree" Approach -> That's definitely bad practise, but it's not Fetch Content :)

Downloading build dependencies into your local tree's build prefix during build time is a bad idea if you have a system package manager. If you don't have the latter, you need to ask yourself why you are still using a platform that is crippled and how productive you can expect yourself to be.
